version: "3"
services:
  front-container:
    image: stevymonkam/front5:1.0
    ports:
      - "83:80"
    networks:
      - springmysql-net
    container_name: front-container
    volumes:
      - front-data:/usr/share/nginx/html
    detach: true  # Déplacer cette ligne à l'intérieur de la définition du service

volumes:
  front-data:
    driver: local

